---

- name: yum install yum install curl-devel
  yum: name=curl-devel state=latest

- name: yum install expat-devel
  yum: name=expat-devel state=latest

- name: yum install gettext-devel
  yum: name=gettext-devel state=latest

- name: yum install openssl-devel
  yum: name=openssl-devel state=latest

- name: yum install zlib-devel
  yum: name=zlib-devel state=latest

- name: yum install perl-ExtUtils-MakeMaker
  yum: name=perl-ExtUtils-MakeMaker state=latest

- name: wget git
  get_url: url=https://www.kernel.org/pub/software/scm/git/git-{{ git_version }}.tar.gz dest={{ src_dir }}

- name: unarchive git-{{ git_version }}.tar.gz
  unarchive:
    src: "{{ src_dir }}/git-{{ git_version }}.tar.gz"
    dest: "/usr/local/"
    copy: no

- name: make prefix=/usr/local all
  command: chdir=/usr/local/git-{{ git_version }} make prefix=/usr/local all
  become: yes

- name: make prefix=/usr/local install
  command: chdir=/usr/local/git-{{ git_version }} make prefix=/usr/local install
  become: yes

- name: yum install mercurial
  yum: name=mercurial state=latest
