---

- hosts: webservers
  sudo: yes
  gather_facts: no
  tasks:
  roles:
   - role: common
     tags: [common]
#    - role: vim
#      tags: [vim]
#      when: inventory_file | basename == 'develop'
#    - role: mysql-devel
#      tags: [mysql-devel]
#    - role: openssl
#      tags: [openssl]
#    - role: apache
#      tags: [apache]
   - role: go
     tags: [go]
