# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version '>=1.6.0'

require File.expand_path('mod.rb', File.dirname(__FILE__))
include Vagrants

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'centos65'
  config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box"
  config.ssh.insert_key = false
  config.vm.define :develop do |develop|
    develop.vm.hostname = 'develop'
    develop.vm.network 'private_network', ip: '192.168.33.40'
    develop.vm.network 'private_network', ip: '192.168.33.41'
    develop.ssh.forward_agent = true
    develop.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '1024', '--cpus', '1', '--ioapic', 'on']
    end
    Vagrants.port_forwarding(develop.vm, :'3000' => 13000)
  end
  Vagrants.ansible_playbook(config.vm, 'site.yml')
end
